### ISSUE TITLE
Multi-Duration Saliency

### ISSUE THREAD

**Issue by ghost** [turkeyes/zoommaps#10]
Hi there,
Thank you for your hard work,

is there a link to the code of "Multi-Duration Saliency", since the github repository hat was posted in the paper in not working.

**Comment by a-newman** [comment]
Hello, 

Here's the multi-duration saliency code: https://github.com/diviz-mit/multiduration-saliency 
You can find the link and other resources on our website: http://multiduration-saliency.csail.mit.edu/

(The repo was set to private previously--thank you for catching this!) 

Anelise
